--[[
    init.lua
    Created: 04/16/2021 09:16:46
    Description: Autogenerated script file for the map grove_entrance.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local grove_entrance = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---grove_entrance.Init
--Engine callback function
function grove_entrance.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---grove_entrance.Enter
--Engine callback function
function grove_entrance.Enter(map)

  if not SV.grove_entrance.IntroComplete then
    grove_entrance.Cutscene()
  else
    GAME:FadeIn(20)
  end
  
  SV.grove_entrance.IntroComplete = true

end

---grove_entrance.Exit
--Engine callback function
function grove_entrance.Exit(map)


end

---grove_entrance.Update
--Engine callback function
function grove_entrance.Update(map)


end

function grove_entrance.Cutscene()
  --Hide assembly and storage
  GAME:UnlockDungeon("mystery_grove")
  
  local starter = CH('PLAYER')
  
  GROUND:CharSetAnim(starter, 'Sleep', true)
  UI:SetSpeaker(starter)
  
  GAME:WaitFrames(60)
  
  if starter.Data.BaseForm.Species == "ditto" then
    UI:WaitShowDialogue("Yawwwwn...")
  GAME:WaitFrames(30)
    GAME:FadeIn(60)
  GAME:WaitFrames(60)
	UI:WaitShowDialogue("Sleepy sleepy...")
	-- wake up
	GROUND:CharSetAnim(starter, 'None', true)
  GAME:WaitFrames(40)
	UI:WaitShowDialogue("Another wonderful morning on the trail![pause=0] Next stop, Pe'kemon City!")
	UI:WaitShowDialogue("Did you sleep well, Lumiere?")
	-- look around
	
	local turnTime = 4
	SOUND:PlayBattleSE("EVT_Emote_Confused")
  GROUND:CharAnimateTurnTo(starter, Direction.Left, turnTime)
  GAME:WaitFrames(40)
  SOUND:PlayBattleSE("EVT_Emote_Confused")
  GROUND:CharAnimateTurn(starter, Direction.Right, turnTime, true)
  GAME:WaitFrames(40)
  GROUND:CharAnimateTurnTo(starter, Direction.Up, turnTime)
  GAME:WaitFrames(60)
  
	UI:WaitShowDialogue("Lumiere...?")
  else
	UI:WaitShowDialogue("Zzz...[pause=30] Zzz...")
  GAME:WaitFrames(30)
    GAME:FadeIn(60)
  GAME:WaitFrames(60)
	-- wake up, exclaim!
	GROUND:CharSetAnim(starter, 'None', true)
    SOUND:PlayBattleSE("EVT_Emote_Exclaim")
    GROUND:CharSetEmote(starter, "notice", 1)
	UI:WaitShowDialogue("Wha?[pause=0] Where am I?")
	UI:WaitShowDialogue("I don't remember napping here...")
	UI:WaitShowDialogue("Melanie, did you carry me off as a Ponyta again?")
	-- look around
	
	local turnTime = 4
	SOUND:PlayBattleSE("EVT_Emote_Confused")
  GROUND:CharAnimateTurnTo(starter, Direction.Left, turnTime)
  GAME:WaitFrames(40)
  SOUND:PlayBattleSE("EVT_Emote_Confused")
  GROUND:CharAnimateTurn(starter, Direction.Right, turnTime, true)
  GAME:WaitFrames(40)
  GROUND:CharAnimateTurnTo(starter, Direction.Up, turnTime)
  GAME:WaitFrames(60)
  
	UI:WaitShowDialogue("I'd better find her...")
  end
  
  GROUND:CharEndAnim(starter)
end

-------------------------------
-- Entities Callbacks
-------------------------------

function grove_entrance.Exit_Touch(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  local dungeon_entrances = { "mystery_grove" }
  local ground_entrances = { }
  COMMON.ShowDestinationMenu(dungeon_entrances,ground_entrances)
end

function grove_entrance.Storage_Action(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  COMMON:ShowTeamStorageMenu()
end


return grove_entrance

