--[[
    init.lua
    Created: 04/16/2021 09:17:51
    Description: Autogenerated script file for the map crystal_entrance.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local crystal_entrance = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---crystal_entrance.Init
--Engine callback function
function crystal_entrance.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

  COMMON.RespawnPartner(true)
end

---crystal_entrance.Enter
--Engine callback function
function crystal_entrance.Enter(map)

  if not SV.crystal_entrance.IntroComplete then
    crystal_entrance.Cutscene()
  else
    GAME:FadeIn(20)
  end
  
  SV.crystal_entrance.IntroComplete = true


end

---crystal_entrance.Exit
--Engine callback function
function crystal_entrance.Exit(map)


end

---crystal_entrance.Update
--Engine callback function
function crystal_entrance.Update(map)


end


function crystal_entrance.Cutscene()

  GAME:UnlockDungeon(3)
  SV.checkpoint = 
  {
    Zone    = 1, Segment  = -1,
    Map  = 3, Entry  = 0
  }
  
  GAME:CutsceneMode(true)
  GAME:FadeIn(20)
  
  local player = CH('PLAYER')
  local partner = CH('Partner')
  
  SOUND:PlayBattleSE("EVT_Emote_Exclaim_2")
  GROUND:CharSetEmote(partner, 3, 1)
  GROUND:CharSetEmote(player, 3, 1)
  
  UI:SetSpeaker(player)
  UI:WaitShowDialogue("Wha?")
  UI:SetSpeaker(partner)
  UI:WaitShowDialogue("Whoa!")
  
  
  local coro1 = TASK:BranchCoroutine(function() crystal_entrance.Concurrent_Sequence(player, false) end)
  local coro2 = TASK:BranchCoroutine(function() crystal_entrance.Concurrent_Sequence(partner, true) end)
  
  TASK:JoinCoroutines({coro1, coro2})
  
  GAME:WaitFrames(30)
  
  if player.Data.BaseForm.Species == 132 then
    UI:SetSpeaker(player)
    UI:WaitShowDialogue("This is so unreal...[pause=0] You didn't draw this with your Mystery Paint, did you?")
    UI:SetSpeaker(partner)
    UI:WaitShowDialogue("What?[pause=0] No, this is way beyond my level of artistry!")
  
    UI:SetSpeaker(player)
    UI:WaitShowDialogue("Aww... are you sure?[pause=0] Some of your backgrounds turn out just as cool as this!")
    GROUND:CharSetEmote(player, 4, 4)
  
    GAME:WaitFrames(90)
  
    UI:SetSpeaker(partner)
    UI:WaitShowDialogue("When I woke up earlier,[pause=30] I thought we just got separated... but this is definitely not normal.")
    UI:WaitShowDialogue("Do you think Pe'kemon City should still be close?")
    UI:SetSpeaker(player)
    UI:WaitShowDialogue("I guess we'll just have to find out.")
  else
  
    UI:SetSpeaker(player)
    UI:WaitShowDialogue("Melanie, are you seeing what I'm seeing?[pause=0] The background just changed!")
    UI:SetSpeaker(partner)
    UI:WaitShowDialogue("I said the trail to Pe'kemon was going to be mysterious, but this isn't what I meant!")
    
    UI:SetSpeaker(player)
    UI:WaitShowDialogue("When I woke up earlier,[pause=30] I thought we just got separated... but this is definitely not normal.")
    UI:WaitShowDialogue("Do you think Pe'kemon City should still be close?")
    UI:SetSpeaker(partner)
    UI:WaitShowDialogue("I guess we'll just have to find out.")
  end
  
  GAME:CutsceneMode(false)
  
  -- lumiere saw kazure earlier
  -- he says that's the culprit when they see it
end

function crystal_entrance.Concurrent_Sequence(chara, goDown)
  
  if goDown then
    GAME:WaitFrames(10)
  end
  
  local turnTime = 4
  GROUND:CharSetAnim(chara, "None", true)
  GROUND:CharAnimateTurnTo(chara, Direction.Left, turnTime)
  GAME:WaitFrames(20)
  SOUND:PlayBattleSE("EVT_Emote_Confused")
  GROUND:CharAnimateTurn(chara, Direction.Right, turnTime, not goDown)
  GAME:WaitFrames(20)
  SOUND:PlayBattleSE("EVT_Emote_Confused")
  GROUND:CharAnimateTurn(chara, Direction.Left, turnTime, goDown)
  GAME:WaitFrames(20)
  GROUND:CharAnimateTurn(chara, Direction.Right, turnTime, not goDown)
  GAME:WaitFrames(40)
  local actualDir = Direction.Up
  if goDown then
    actualDir = Direction.Down
  end
  GROUND:CharAnimateTurnTo(chara, actualDir, turnTime)
  GROUND:CharSetAnim(chara, "None", false)
end

-------------------------------
-- Entities Callbacks
-------------------------------

function crystal_entrance.Exit_Touch(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  local dungeon_entrances = { 3 }
  local ground_entrances = { }
  COMMON.ShowDestinationMenu(dungeon_entrances,ground_entrances)
end

function crystal_entrance.Storage_Action(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  COMMON:ShowTeamStorageMenu()
end


function crystal_entrance.Partner_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  UI:SetSpeaker(chara)
  if chara.Data.BaseForm.Species == 132 then
    UI:WaitShowDialogue("So mysterious![pause=0] I wonder if we'll find more weird Pe'kemon here.")
  else
    UI:WaitShowDialogue("This place is actually quite pretty...[pause=30] I should draw it some time.")
  end
end

return crystal_entrance

