--[[
    init.lua
    Created: 04/16/2021 09:18:16
    Description: Autogenerated script file for the map crystal_exit.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local crystal_exit = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---crystal_exit.Init
--Engine callback function
function crystal_exit.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

  COMMON.RespawnPartner(false)
end

---crystal_exit.Enter
--Engine callback function
function crystal_exit.Enter(map)

  crystal_exit.Cutscene()
  
end

---crystal_exit.Exit
--Engine callback function
function crystal_exit.Exit(map)


end

---crystal_exit.Update
--Engine callback function
function crystal_exit.Update(map)


end


function crystal_exit.Cutscene()
  GAME:CutsceneMode(true)
  
  GAME:MoveCamera(200, 192, 1, false)
  GAME:FadeIn(20)
  
  local player = CH('PLAYER')
  local partner = CH('Partner')
  
  local coro1 = TASK:BranchCoroutine(function() crystal_exit.Concurrent_Sequence() end)
  GROUND:MoveInDirection(partner, Direction.Up, 60, false, 2)
  
  TASK:JoinCoroutines({coro1})
  
  if player.Data.BaseForm.Species == "ditto" then
    UI:SetSpeaker(player)
    UI:WaitShowDialogue("Whew, looks like we're out.[pause=0] Pe'kemon City should be just up ahead.")
    UI:SetSpeaker(partner)
    UI:WaitShowDialogue("Thank Arceus.[pause=0] That cave was gorgeous, but it was so confusing.")
  
    GAME:WaitFrames(30)
    GROUND:CharSetAnim(partner, "Walk", false)
    GAME:WaitFrames(30)
    UI:SetSpeaker(partner)
    UI:WaitShowDialogue("Hey Melanie,[pause=30] what are the 'kemon in the city like?[pause=30] Are they friendly?")
    GAME:WaitFrames(30)
    UI:SetSpeaker(player)
    UI:WaitShowDialogue("Yeah![pause=0] They're all very welcoming,[pause=30] especially if you match their shape~")
    UI:SetSpeaker(partner)
    UI:WaitShowDialogue("Hey wait,[pause=30] what if I can't shapeshift?[pause=0] Are you sure I won't stick out among the city-goers?")
    UI:SetSpeaker(player)
    UI:WaitShowDialogue("No worries![pause=0] Everyone's got a Mystery Aspect and sticks out in some way!")
    UI:SetSpeaker(partner)
    UI:WaitShowDialogue("That's true,[pause=30] Mystery Aspects make even the same species look different...")
    GAME:WaitFrames(30)
    UI:SetSpeaker(player)
    UI:WaitShowDialogue("No one ever makes trouble in Pe'kemon City,[pause=30] the worst you'll see are some pranks.")
    GROUND:CharAnimateTurnTo(player, Direction.Up, 4)
    UI:WaitShowDialogue("You'll see soon enough![pause=0] It should just be over that hill!")
  else
    UI:SetSpeaker(player)
    UI:WaitShowDialogue("It's the light![pause=0] We're finally out!")
    UI:SetSpeaker(partner)
    UI:WaitShowDialogue("What a strange cave that was...[pause=0] Well, Pe'kemon City should be just up ahead.")
	
    GAME:WaitFrames(30)
    GROUND:CharSetAnim(player, "Walk", false)
    GAME:WaitFrames(30)
    UI:SetSpeaker(player)
    UI:WaitShowDialogue("Hey Melanie,[pause=30] tell me more about the 'kemon that live there.[pause=0] You said they all had a Mystery Aspect?")
    GAME:WaitFrames(30)
    UI:SetSpeaker(partner)
    UI:WaitShowDialogue("Mhm![pause=30] Pe'kemon City is the most mysteriosity-high of all places I've seen!")
	
	local origForm = partner.Data.BaseForm
	
	GROUND:CharAnimateTurnTo(player, Direction.Left, 0)
    GROUND:MoveInDirection(partner, Direction.UpLeft, 18, false, 2)
	partner.Data.BaseForm = RogueEssence.Dungeon.MonsterID("altaria", 0, "melanie", Gender.Male)
    GROUND:CharAnimateTurnTo(partner, Direction.Right, 4)
    UI:SetSpeaker(partner)
    UI:WaitShowDialogue("There's Altaria that wears clouds like clothes,")
	
	GROUND:CharAnimateTurnTo(player, Direction.Up, 0)
    GROUND:MoveInDirection(partner, Direction.UpRight, 18, false, 2)
	partner.Data.BaseForm = RogueEssence.Dungeon.MonsterID("pichu", 0, "melanie", Gender.Male)
    GROUND:CharAnimateTurnTo(partner, Direction.Down, 4)
    UI:SetSpeaker(partner)
    UI:WaitShowDialogue("Pichu that can use magnetic powers,")
	
	GROUND:CharAnimateTurnTo(player, Direction.Right, 0)
    GROUND:MoveInDirection(partner, Direction.DownRight, 18, false, 2)
	partner.Data.BaseForm = RogueEssence.Dungeon.MonsterID("mareep", 0, "melanie", Gender.Male)
    GROUND:CharAnimateTurnTo(partner, Direction.Left, 4)
    UI:SetSpeaker(partner)
    UI:WaitShowDialogue("and Mareep that can even fly!")
	
	
	GROUND:CharAnimateTurnTo(player, Direction.Down, 0)
    GROUND:MoveInDirection(partner, Direction.DownLeft, 18, false, 2)
	partner.Data.BaseForm = origForm
    GROUND:CharAnimateTurnTo(partner, Direction.Up, 4)
    GROUND:CharSetEmote(partner, "happy", 4)
	
    UI:SetSpeaker(partner)
    UI:WaitShowDialogue("I can't wait to show you Lumiere,[pause=30] you'll love meeting everyone!")
  end
  
  SOUND:PlayBattleSE("EVT_Fade_White")
  GAME:FadeOut(true, 80)
  
  GAME:EnterGroundMap("mystery_entrance", "entrance")
end


function crystal_exit.Concurrent_Sequence()
  
  local player = CH('PLAYER')
  GROUND:MoveInDirection(player, Direction.Up, 60, false, 2)
  
  local turnTime = 4
  GROUND:CharAnimateTurnTo(player, Direction.Down, turnTime)
end

-------------------------------
-- Entities Callbacks
-------------------------------


return crystal_exit

